# Generated by Django 4.2.1 on 2023-06-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="account_name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.CharField(max_length=512),
        ),
    ]
