# Generated by Django 4.2.1 on 2023-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_customuser_account_name_alter_message_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
