# Generated by Django 4.1 on 2023-02-21 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.CharField(max_length=1024)),
                ('message_date', models.DateTimeField(default=datetime.datetime(2023, 2, 21, 16, 36, 9, 284281, tzinfo=datetime.timezone.utc))),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Message_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.ManyToManyField(null=True, related_name='Chat_Message', to='app.message')),
                ('user', models.ManyToManyField(related_name='Chat_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
