# Generated by Django 4.1 on 2023-02-06 21:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=16, verbose_name="Ім'я")),
                ('second_name', models.CharField(max_length=16, verbose_name='Прізвище')),
                ('account_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Назва аккаунту')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефону')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=False, verbose_name='Є активним?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Має доступ до адмін панелі?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Є суперюзером?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
