# Generated by Django 4.1 on 2023-02-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Назва аккаунту'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('first_name', 'second_name')},
        ),
    ]
